import { createHash } from "node:crypto";

import { Ajv2020 } from "ajv/dist/2020.js";
import { describe, expect, it } from "vitest";

import {
  canonicalSha256,
  capabilitySchemaProjectionSchema,
  coreContractVersion,
  getCapabilityDefinitionSnapshot,
  projectCapabilities,
  readCapabilityRegistry,
  safeParseCapabilityData,
  safeParseCapabilityInput,
} from "../../src/core/index.js";

const independentCanonicalJson = (value: unknown): string => {
  if (value === null || typeof value === "string" || typeof value === "boolean") {
    return JSON.stringify(value);
  }
  if (typeof value === "number" && Number.isFinite(value)) return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(independentCanonicalJson).join(",")}]`;
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>)
      .sort(([left], [right]) => left < right ? -1 : left > right ? 1 : 0);
    return `{${entries.map(([key, entry]) =>
      `${JSON.stringify(key)}:${independentCanonicalJson(entry)}`).join(",")}}`;
  }
  throw new TypeError("Unsupported test canonical JSON value.");
};

const independentSha256 = (value: unknown): string =>
  createHash("sha256").update(independentCanonicalJson(value), "utf8").digest("hex");

describe("generated capability projections", () => {
  const golden = {
    "account.balance": [
      "3d89aef20725193ca708b52657244a3778edcc30cf31d7f604474369fbcfd808",
      "3a0a63c586e414f4c4f5dfbaa802efb30224015c60df190b60bb29bd9faa63d4",
      "f55288eca4c782af47b739af615ac6cc111fa98045bf5fb294d5340328fc8068",
    ],
    "chain.status": [
      "e6893194491eaba247ecf98b217f51330530ed59df367986ca947acaa3690e3a",
      "69f497f967536e51a9096759248380e1d8b0ffe656d2facdf1155906ca5099bd",
      "426efb45d85ad864b1b151d3addcac0d64d1ba94754ff2af84a13a548ccffefe",
    ],
    "contract.inspect": [
      "02254b12fce67d0f818a6d350f6cfb5afd02b1ceb5edb0b8cda79b560e6e3e45",
      "79e34295119a8ee14e48ccb26f50cbaf4d4de3b5f85121128650949ba38deafa",
      "fe30e232f8900ccb2be2b8ab2f869bd1c87eb81c26109e596663c83fb4d6cb5c",
    ],
    "transaction.inspect": [
      "3f0fb554304a809b89147884a237c5250f6de0414a687aef51ac463838bbd948",
      "8bcfe78a48cf4fd8f6134fc6cd3fdd2206d5ab03347f555385689290d6fdd95a",
      "fcb472110feaa8a8afa5a4f4e7b34e26854c73615230b0a5e12247696c31a089",
    ],
    "wallet.connection": [
      "5cb46c654e67be83b0e6ce7b269a8ccdb5c13c1adca3f815e43ef219149bb923",
      "56b5709814fcb74befae6ef80fd3f7cf15d06e153cff1c92db83cbc7ded77be8",
      "59671cad4a88e778443f2a99a0373097b99952f6031303c0628bcf89befb0030",
    ],
  } as const;

  it("projects one unique schema identity and digest from each canonical definition", () => {
    const projections = projectCapabilities(readCapabilityRegistry);
    const ids = projections.flatMap((projection) => [
      projection.input.schemaId,
      projection.data.schemaId,
      projection.success.schemaId,
    ]);
    expect(new Set(ids).size).toBe(ids.length);
    for (const projection of projections) {
      const definition = readCapabilityRegistry.get(projection.capabilityId);
      expect(projection.input.schemaId).toBe(
        `urn:littlejohn:capability:${projection.capabilityId}:input:v${coreContractVersion}`,
      );
      expect(projection.data.schemaId).toBe(
        `urn:littlejohn:capability:${projection.capabilityId}:data:v${coreContractVersion}`,
      );
      expect(projection.success.schemaId).toBe(
        `urn:littlejohn:capability:${projection.capabilityId}:success:v${coreContractVersion}`,
      );
      expect(projection.contractVersion).toBe(coreContractVersion);
      expect(projection.maximumSuccessUtf8Bytes).toBe(8_388_607);
      expect(canonicalSha256(projection.input.schema)).toBe(projection.input.digest);
      expect(canonicalSha256(projection.data.schema)).toBe(projection.data.digest);
      expect(canonicalSha256(projection.success.schema)).toBe(projection.success.digest);
      expect(projection.failureCodes).toEqual(
        getCapabilityDefinitionSnapshot(definition).failureCodes,
      );
      expect(projection.failureCodes.filter((code) => code === "result_too_large")).toHaveLength(1);
      expect(Object.isFrozen(projection.failureCodes)).toBe(true);
    }
  });

  it("matches fixed schema digests that cannot be regenerated by the assertion", () => {
    const projections = projectCapabilities(readCapabilityRegistry);
    for (const projection of projections) {
      const expected = golden[projection.capabilityId as keyof typeof golden];
      expect([
        independentSha256(projection.input.schema),
        independentSha256(projection.data.schema),
        independentSha256(projection.success.schema),
      ]).toEqual(expected);
      expect([projection.input.digest, projection.data.digest, projection.success.digest])
        .toEqual(expected);
    }
  });

  it("makes the aggregate success budget part of every canonical projection", () => {
    for (const projection of projectCapabilities(readCapabilityRegistry)) {
      expect(capabilitySchemaProjectionSchema.safeParse(projection).success).toBe(true);
      const { maximumSuccessUtf8Bytes: _omitted, ...missing } = projection;
      expect(capabilitySchemaProjectionSchema.safeParse(missing).success).toBe(false);
      expect(capabilitySchemaProjectionSchema.safeParse({
        ...projection,
        maximumSuccessUtf8Bytes: 8_388_608,
      }).success).toBe(false);
    }
  });

  it("emits JSON Schemas that independently reject unknown input fields", () => {
    const projection = projectCapabilities(readCapabilityRegistry)
      .find((candidate) => candidate.capabilityId === "contract.inspect");
    expect(projection).toBeDefined();
    const ajv = new Ajv2020({ strict: true });
    const validate = ajv.compile(projection?.input.schema as object);
    expect(validate({ address: `0x${"1".repeat(40)}`, block: { kind: "latest" } })).toBe(true);
    expect(validate({ address: `0x${"1".repeat(40)}`, block: { kind: "latest" }, extra: true })).toBe(false);
    expect(validate({
      address: "0x52908400098527886E0F7030069857D2E4169EE7",
      block: { kind: "latest" },
    })).toBe(true);
  });

  it("keeps Zod and JSON Schema aligned for the JavaScript prototype key", () => {
    const projections = projectCapabilities(readCapabilityRegistry);
    const ajv = new Ajv2020({ strict: true });
    const noInput = JSON.parse('{"__proto__":[]}') as unknown;
    const chain = readCapabilityRegistry.get("chain.status");
    const chainProjection = projections.find((candidate) => candidate.capabilityId === "chain.status");
    const validateChain = ajv.compile(chainProjection?.input.schema as object);
    expect(validateChain(noInput)).toBe(false);
    expect(safeParseCapabilityInput(chain, noInput).success).toBe(false);

    const nested = JSON.parse(`{
      "address":"0x${"1".repeat(40)}",
      "block":{"kind":"latest","__proto__":[]}
    }`) as unknown;
    const contract = readCapabilityRegistry.get("contract.inspect");
    const contractProjection = projections.find((candidate) => candidate.capabilityId === "contract.inspect");
    const validateContract = ajv.compile(contractProjection?.input.schema as object);
    expect(validateContract(nested)).toBe(false);
    expect(safeParseCapabilityInput(contract, nested).success).toBe(false);
  });

  it("preserves account input acceptance for cross-field and set constraints", () => {
    const projection = projectCapabilities(readCapabilityRegistry)
      .find((candidate) => candidate.capabilityId === "account.balance");
    expect(projection).toBeDefined();
    const validate = new Ajv2020({ strict: true }).compile(projection?.input.schema as object);
    const addressA = `0x${"1".repeat(40)}`;
    const addressB = `0x${"2".repeat(40)}`;
    const base = {
      account: { kind: "address", address: addressA },
      includeNative: false,
      block: { kind: "latest" },
    };
    for (const candidate of [
      { ...base, tokens: [addressA] },
      { ...base, tokens: [addressB, addressA] },
      { ...base, tokens: [addressA, addressA] },
      { ...base, tokens: [] },
    ]) {
      const zodAccepted = safeParseCapabilityInput(
        readCapabilityRegistry.get("account.balance"),
        candidate,
      ).success;
      expect(validate(candidate)).toBe(zodAccepted);
    }
  });

  it("projects wallet structure while the canonical definition retains intrinsic meaning", () => {
    const projection = projectCapabilities(readCapabilityRegistry)
      .find((candidate) => candidate.capabilityId === "wallet.connection");
    const validate = new Ajv2020({ strict: true }).compile(projection?.data.schema as object);
    const address = `0x${"1".repeat(40)}`;
    const connected = {
      status: "connected",
      address,
      chainId: "eip155:4663",
      approvedMethods: ["eth_sendTransaction"],
      approvedEvents: ["accountsChanged", "chainChanged"],
      expiresAt: "2026-07-13T10:16:02.000Z",
    };
    expect(validate(connected)).toBe(true);
    expect(safeParseCapabilityData(readCapabilityRegistry.get("wallet.connection"), connected).success).toBe(true);
    expect(validate({ ...connected, account: `${connected.chainId}:${connected.address}` })).toBe(false);
    expect(validate({ ...connected, address: `0x${"A".repeat(40)}` })).toBe(false);
    const missingMethod = { ...connected, approvedMethods: [] };
    expect(validate(missingMethod)).toBe(true);
    expect(safeParseCapabilityData(readCapabilityRegistry.get("wallet.connection"), missingMethod).success).toBe(true);
    expect(validate({ status: "unresolved", sessionCount: "2" })).toBe(true);
    expect(validate({ status: "unresolved", sessionCount: "1" })).toBe(false);
    expect(validate({ status: "unresolved", eligibleSessionCount: "2" })).toBe(false);
  });

  it("contains no version-one schema identity", () => {
    expect(JSON.stringify(projectCapabilities(readCapabilityRegistry))).not.toContain(":v1");
  });
});
