import { Ajv2020 } from "ajv/dist/2020.js";
import { describe, expect, it } from "vitest";

import {
  canonicalSha256,
  getCapabilityDefinitionSnapshot,
  projectCapabilities,
  readCapabilityRegistry,
  safeParseCapabilityData,
  safeParseCapabilityInput,
} from "../../src/core/index.js";

describe("generated capability projections", () => {
  const golden = {
    "account.balance": [
      "fb9ecc3dab813f084291280ff8a88bc82f7d34dc125c36929c4cde1f2d3aaaae",
      "d75f6d5245f13ced3b5894ea5f280b92e12ffacfde1e6e5533c83af228760526",
      "c0d659f485f7ef6e533ae5eba6f00991d034f7ead60dd9b9a45219a51ba366ad",
    ],
    "chain.status": [
      "e26cb5e8480ef708cd739ac63103c97908c1c9469d32ca96bfa7a51184490bcd",
      "73971577577f702d1be32df067bb64f62729bc425ab6c7fc20925d72af4f8492",
      "f2a3454e7a61b1808d577bbeffb724b426e651f4d925a578ebc64040f6c4811a",
    ],
    "contract.inspect": [
      "94623c848b50fe567124714c5f6b0a169d7d285d9d047edfa517774c2755bdf6",
      "964d4e514e82874152674569b4ea631e084880fa86715d4f2cf0078da18ad14d",
      "f2cbc6ad97e8f4f614b396eb10d699216c3356a6e92fa6200d2caf74dcaa916b",
    ],
    "transaction.inspect": [
      "c229b4dfb207cbec37d109faa9fbdb95084fd4f43a9dba7ea2c1c9c8b80936f7",
      "0225ce59075577bf72ac038c7ca79f7a71645e15b3744553ed0363843a708547",
      "c5c03321877c232efedc0ad0f37825d382e979ac720ef955184f481985606492",
    ],
    "wallet.connection": [
      "3c5e10f6236f85d6270dcca3742df813ab1d9a9e7fc575f025dc5f0a96679d4e",
      "dcc87d007108306c6919099d572243d3ec4206b9eefb5d23e1b8f115236d3b6c",
      "585d347855ffb491ab3e1acbbcd57c4fdc1c78d42b3c789100b760a8c40fe61f",
    ],
  } as const;

  it("projects one unique schema identity and digest from each canonical definition", () => {
    const projections = projectCapabilities(readCapabilityRegistry);
    const ids = projections.flatMap((projection) => [
      projection.input.schemaId,
      projection.data.schemaId,
      projection.success.schemaId,
    ]);
    expect(new Set(ids).size).toBe(ids.length);
    for (const projection of projections) {
      const definition = readCapabilityRegistry.get(projection.capabilityId);
      expect(projection.input.schemaId).toBe(`urn:littlejohn:capability:${projection.capabilityId}:input:v1`);
      expect(projection.data.schemaId).toBe(`urn:littlejohn:capability:${projection.capabilityId}:data:v1`);
      expect(projection.success.schemaId).toBe(`urn:littlejohn:capability:${projection.capabilityId}:success:v1`);
      expect(canonicalSha256(projection.input.schema)).toBe(projection.input.digest);
      expect(canonicalSha256(projection.data.schema)).toBe(projection.data.digest);
      expect(canonicalSha256(projection.success.schema)).toBe(projection.success.digest);
      expect(projection.failureCodes).toEqual(
        getCapabilityDefinitionSnapshot(definition).failureCodes,
      );
      expect(Object.isFrozen(projection.failureCodes)).toBe(true);
    }
  });

  it("matches fixed schema digests that cannot be regenerated by the assertion", () => {
    const projections = projectCapabilities(readCapabilityRegistry);
    for (const projection of projections) {
      expect([projection.input.digest, projection.data.digest, projection.success.digest]).toEqual(
        golden[projection.capabilityId as keyof typeof golden],
      );
    }
  });

  it("emits JSON Schemas that independently reject unknown input fields", () => {
    const projection = projectCapabilities(readCapabilityRegistry)
      .find((candidate) => candidate.capabilityId === "contract.inspect");
    expect(projection).toBeDefined();
    const ajv = new Ajv2020({ strict: true });
    const validate = ajv.compile(projection?.input.schema as object);
    expect(validate({ address: `0x${"1".repeat(40)}`, block: { kind: "latest" } })).toBe(true);
    expect(validate({ address: `0x${"1".repeat(40)}`, block: { kind: "latest" }, extra: true })).toBe(false);
  });

  it("keeps Zod and JSON Schema aligned for the JavaScript prototype key", () => {
    const projections = projectCapabilities(readCapabilityRegistry);
    const ajv = new Ajv2020({ strict: true });
    const noInput = JSON.parse('{"__proto__":[]}') as unknown;
    const chain = readCapabilityRegistry.get("chain.status");
    const chainProjection = projections.find((candidate) => candidate.capabilityId === "chain.status");
    const validateChain = ajv.compile(chainProjection?.input.schema as object);
    expect(validateChain(noInput)).toBe(false);
    expect(safeParseCapabilityInput(chain, noInput).success).toBe(false);

    const nested = JSON.parse(`{
      "address":"0x${"1".repeat(40)}",
      "block":{"kind":"latest","__proto__":[]}
    }`) as unknown;
    const contract = readCapabilityRegistry.get("contract.inspect");
    const contractProjection = projections.find((candidate) => candidate.capabilityId === "contract.inspect");
    const validateContract = ajv.compile(contractProjection?.input.schema as object);
    expect(validateContract(nested)).toBe(false);
    expect(safeParseCapabilityInput(contract, nested).success).toBe(false);
  });

  it("preserves account input acceptance for cross-field and set constraints", () => {
    const projection = projectCapabilities(readCapabilityRegistry)
      .find((candidate) => candidate.capabilityId === "account.balance");
    expect(projection).toBeDefined();
    const validate = new Ajv2020({ strict: true }).compile(projection?.input.schema as object);
    const addressA = `0x${"1".repeat(40)}`;
    const addressB = `0x${"2".repeat(40)}`;
    const base = {
      account: { kind: "address", address: addressA },
      includeNative: false,
      block: { kind: "latest" },
    };
    for (const candidate of [
      { ...base, tokens: [addressA] },
      { ...base, tokens: [addressB, addressA] },
      { ...base, tokens: [addressA, addressA] },
      { ...base, tokens: [] },
    ]) {
      const zodAccepted = safeParseCapabilityInput(
        readCapabilityRegistry.get("account.balance"),
        candidate,
      ).success;
      expect(validate(candidate)).toBe(zodAccepted);
    }
  });

  it("projects wallet structure while the canonical definition retains intrinsic meaning", () => {
    const projection = projectCapabilities(readCapabilityRegistry)
      .find((candidate) => candidate.capabilityId === "wallet.connection");
    const validate = new Ajv2020({ strict: true }).compile(projection?.data.schema as object);
    const address = `0x${"1".repeat(40)}`;
    const connected = {
      status: "connected",
      account: `eip155:4663:${address}`,
      address,
      chainId: "eip155:4663",
      approvedMethods: ["eth_sendTransaction"],
      approvedEvents: ["accountsChanged", "chainChanged"],
      expiresAt: "2026-07-13T10:16:02.000Z",
    };
    expect(validate(connected)).toBe(true);
    expect(safeParseCapabilityData(readCapabilityRegistry.get("wallet.connection"), connected).success).toBe(true);
    const missingMethod = { ...connected, approvedMethods: [] };
    expect(validate(missingMethod)).toBe(true);
    expect(safeParseCapabilityData(readCapabilityRegistry.get("wallet.connection"), missingMethod).success).toBe(false);
    expect(validate({ status: "unresolved", eligibleSessionCount: "2" })).toBe(true);
    expect(validate({ status: "unresolved", eligibleSessionCount: "1" })).toBe(false);
  });
});
