import { Ajv2020 } from "ajv/dist/2020.js";
import { describe, expect, it } from "vitest";

import {
  canonicalSha256,
  capabilitySchemaProjectionSchema,
  coreContractVersion,
  getCapabilityDefinitionSnapshot,
  projectCapabilities,
  readCapabilityRegistry,
  safeParseCapabilityData,
  safeParseCapabilityInput,
} from "../../src/core/index.js";

describe("generated capability projections", () => {
  const golden = {
    "account.balance": [
      "be04aa06e5915821efc4e28602e175221b68fa0ad436ab44d98a171b36f35351",
      "9a1ce3a6a5e9b681f20c1e84b2910683b4919403767cb2c553e28153d67d0e94",
      "5cc7d60863a2f7413f7747e0a141b4b3ca85a843902d016863d7dc6bcbf6ba09",
    ],
    "chain.status": [
      "ed12e01397346c7998e9950e7e53e14206b59a9acca7ec2c2b83c7a6f8fe16aa",
      "698b99fae23384a0d8f6f1dfe5ca2c5c36980aab9398827e81670d47dcb6cde9",
      "30cf139e6492bea7ca1d3186724d4a5461912f0eb5dc866ae657bf1c80d7777f",
    ],
    "contract.inspect": [
      "2ba906c7ec25e3c13bf18d4d0cff6aa9662f80b1cafce5f49254f869bc951ffa",
      "f0b7f78bacb177cdca005d2750ef49c980ce5927ba0a1071ccde2bc8d9ac0dec",
      "b16d624488de290a4bcabaa95e6efb70721dbae5b41438039feb019055be3228",
    ],
    "transaction.inspect": [
      "54c2075cb9c0db34bd477d2caa27d5c68cb52d9f6e9743152756271f61011458",
      "ae5c17c386bf58fb547a32ef875e9270815d8f53594557ae10e40f58c91a4048",
      "0db57cd02d216ce3e97c60a2a2571ca1bc6323993871c711ed38a1d747069e78",
    ],
    "wallet.connection": [
      "e062d8dc5c584cfc22635628d10461c52ab38385795ae8f1db80823a3d909793",
      "739ab8c3e2e3077f5baad8af7f0d2ea908368b58602deb6152a4dbb5df007b77",
      "a4c3d451c7ca8659192d57101d6f353d3b13401df0fa9fd87cc4fd2fb3fa52cd",
    ],
  } as const;

  it("projects one unique schema identity and digest from each canonical definition", () => {
    const projections = projectCapabilities(readCapabilityRegistry);
    const ids = projections.flatMap((projection) => [
      projection.input.schemaId,
      projection.data.schemaId,
      projection.success.schemaId,
    ]);
    expect(new Set(ids).size).toBe(ids.length);
    for (const projection of projections) {
      const definition = readCapabilityRegistry.get(projection.capabilityId);
      expect(projection.input.schemaId).toBe(
        `urn:littlejohn:capability:${projection.capabilityId}:input:v${coreContractVersion}`,
      );
      expect(projection.data.schemaId).toBe(
        `urn:littlejohn:capability:${projection.capabilityId}:data:v${coreContractVersion}`,
      );
      expect(projection.success.schemaId).toBe(
        `urn:littlejohn:capability:${projection.capabilityId}:success:v${coreContractVersion}`,
      );
      expect(projection.contractVersion).toBe(coreContractVersion);
      expect(projection.maximumSuccessUtf8Bytes).toBe(8_388_607);
      expect(canonicalSha256(projection.input.schema)).toBe(projection.input.digest);
      expect(canonicalSha256(projection.data.schema)).toBe(projection.data.digest);
      expect(canonicalSha256(projection.success.schema)).toBe(projection.success.digest);
      expect(projection.failureCodes).toEqual(
        getCapabilityDefinitionSnapshot(definition).failureCodes,
      );
      expect(projection.failureCodes.filter((code) => code === "result_too_large")).toHaveLength(1);
      expect(Object.isFrozen(projection.failureCodes)).toBe(true);
    }
  });

  it("matches fixed schema digests that cannot be regenerated by the assertion", () => {
    const projections = projectCapabilities(readCapabilityRegistry);
    for (const projection of projections) {
      expect([projection.input.digest, projection.data.digest, projection.success.digest]).toEqual(
        golden[projection.capabilityId as keyof typeof golden],
      );
    }
  });

  it("makes the aggregate success budget part of every canonical projection", () => {
    for (const projection of projectCapabilities(readCapabilityRegistry)) {
      expect(capabilitySchemaProjectionSchema.safeParse(projection).success).toBe(true);
      const { maximumSuccessUtf8Bytes: _omitted, ...missing } = projection;
      expect(capabilitySchemaProjectionSchema.safeParse(missing).success).toBe(false);
      expect(capabilitySchemaProjectionSchema.safeParse({
        ...projection,
        maximumSuccessUtf8Bytes: 8_388_608,
      }).success).toBe(false);
    }
  });

  it("emits JSON Schemas that independently reject unknown input fields", () => {
    const projection = projectCapabilities(readCapabilityRegistry)
      .find((candidate) => candidate.capabilityId === "contract.inspect");
    expect(projection).toBeDefined();
    const ajv = new Ajv2020({ strict: true });
    const validate = ajv.compile(projection?.input.schema as object);
    expect(validate({ address: `0x${"1".repeat(40)}`, block: { kind: "latest" } })).toBe(true);
    expect(validate({ address: `0x${"1".repeat(40)}`, block: { kind: "latest" }, extra: true })).toBe(false);
    expect(validate({
      address: "0x52908400098527886E0F7030069857D2E4169EE7",
      block: { kind: "latest" },
    })).toBe(true);
  });

  it("keeps Zod and JSON Schema aligned for the JavaScript prototype key", () => {
    const projections = projectCapabilities(readCapabilityRegistry);
    const ajv = new Ajv2020({ strict: true });
    const noInput = JSON.parse('{"__proto__":[]}') as unknown;
    const chain = readCapabilityRegistry.get("chain.status");
    const chainProjection = projections.find((candidate) => candidate.capabilityId === "chain.status");
    const validateChain = ajv.compile(chainProjection?.input.schema as object);
    expect(validateChain(noInput)).toBe(false);
    expect(safeParseCapabilityInput(chain, noInput).success).toBe(false);

    const nested = JSON.parse(`{
      "address":"0x${"1".repeat(40)}",
      "block":{"kind":"latest","__proto__":[]}
    }`) as unknown;
    const contract = readCapabilityRegistry.get("contract.inspect");
    const contractProjection = projections.find((candidate) => candidate.capabilityId === "contract.inspect");
    const validateContract = ajv.compile(contractProjection?.input.schema as object);
    expect(validateContract(nested)).toBe(false);
    expect(safeParseCapabilityInput(contract, nested).success).toBe(false);
  });

  it("preserves account input acceptance for cross-field and set constraints", () => {
    const projection = projectCapabilities(readCapabilityRegistry)
      .find((candidate) => candidate.capabilityId === "account.balance");
    expect(projection).toBeDefined();
    const validate = new Ajv2020({ strict: true }).compile(projection?.input.schema as object);
    const addressA = `0x${"1".repeat(40)}`;
    const addressB = `0x${"2".repeat(40)}`;
    const base = {
      account: { kind: "address", address: addressA },
      includeNative: false,
      block: { kind: "latest" },
    };
    for (const candidate of [
      { ...base, tokens: [addressA] },
      { ...base, tokens: [addressB, addressA] },
      { ...base, tokens: [addressA, addressA] },
      { ...base, tokens: [] },
    ]) {
      const zodAccepted = safeParseCapabilityInput(
        readCapabilityRegistry.get("account.balance"),
        candidate,
      ).success;
      expect(validate(candidate)).toBe(zodAccepted);
    }
  });

  it("projects wallet structure while the canonical definition retains intrinsic meaning", () => {
    const projection = projectCapabilities(readCapabilityRegistry)
      .find((candidate) => candidate.capabilityId === "wallet.connection");
    const validate = new Ajv2020({ strict: true }).compile(projection?.data.schema as object);
    const address = `0x${"1".repeat(40)}`;
    const connected = {
      status: "connected",
      address,
      chainId: "eip155:4663",
      approvedMethods: ["eth_sendTransaction"],
      approvedEvents: ["accountsChanged", "chainChanged"],
      expiresAt: "2026-07-13T10:16:02.000Z",
    };
    expect(validate(connected)).toBe(true);
    expect(safeParseCapabilityData(readCapabilityRegistry.get("wallet.connection"), connected).success).toBe(true);
    expect(validate({ ...connected, account: `${connected.chainId}:${connected.address}` })).toBe(false);
    expect(validate({ ...connected, address: `0x${"A".repeat(40)}` })).toBe(false);
    const missingMethod = { ...connected, approvedMethods: [] };
    expect(validate(missingMethod)).toBe(true);
    expect(safeParseCapabilityData(readCapabilityRegistry.get("wallet.connection"), missingMethod).success).toBe(true);
    expect(validate({ status: "unresolved", sessionCount: "2" })).toBe(true);
    expect(validate({ status: "unresolved", sessionCount: "1" })).toBe(false);
    expect(validate({ status: "unresolved", eligibleSessionCount: "2" })).toBe(false);
  });

  it("contains no version-one schema identity", () => {
    expect(JSON.stringify(projectCapabilities(readCapabilityRegistry))).not.toContain(":v1");
  });
});
