// Generated by npm run generate:stock-token-reference-market. Do not edit.

export const stockTokenReferenceMarketGeneratedCatalog = {
  "contractVersion": "1",
  "sources": [
    {
      "uri": "https://api.robinhood.com/rhj/assets",
      "observedAt": "2026-08-12T13:12:28.000Z",
      "rawResponseBytes": 76348,
      "rawResponseDigest": "0xb0b8146f0901ab22d9006cd2c2603cc7d2551aec2ca307ce35334aca2a6f146b"
    },
    {
      "uri": "https://reference-data-directory.vercel.app/feeds-robinhood-mainnet.json",
      "observedAt": "2026-08-12T13:12:48.000Z",
      "rawResponseBytes": 79741,
      "rawResponseDigest": "0x1f9d96f1f3f25be68f299a20c99457288e8cf2f69748962360ecb6dd8824a434"
    }
  ],
  "dispositionSetDigest": "0xb995fcea74b35f8d4f9f037f9b6e7848c08414c145784e620fdff43d801f8efe",
  "dispositions": [
    {
      "asset": {
        "assetUid": "0x0000000000000000000000000000000002c4d1ce31ec4310b2c507c921a52b70",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "P",
        "name": "Everpure • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x1cdad396db64bda184d5182a97dd9b3c62100b7d",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x0000000000000000000000000000000004a960b45163413698f0f69b5454785d",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "APLD",
        "name": "Applied Digital • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xb8dbf92f9741c9ac1c32115e78581f23509916fd",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000000a924e0d878747e586c22887bc2d82b1",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "QBTS",
        "name": "D-Wave Quantum Inc. Common Stock • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xc583c60aef9dc401da72cec1b404743a93cea1cc",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000000b2d487cedd9423a890231379e09bbb6",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "SATS",
        "name": "EchoStar • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x95052ddcd5dc25641657424a8cf04834997e1730",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000000cfe41021541408ab92f19e6af2fa729",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "SMCI",
        "name": "Super Micro Computer • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xc01aa1fecec0605b13bc84874ff7256c0f5f562a",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x0000000000000000000000000000000014eaef73a2c44d62b7952cfd0a44ff51",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "DELL",
        "name": "Dell • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x941ae714ec6d8130c7b75d67160ca08f1e7d11dd",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x0000000000000000000000000000000014f96c01ad254647b2617a5686d6053a",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "MXL",
        "name": "MaxLinear • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x48961813349333209994750ffa89b3c5c22ec969",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000001805c8a4eb1a4b3fa49e2698c0da6baa",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "WDAY",
        "name": "Workday • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x82da4646242e1d962e96e932269dc644c94a9caa",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000001aa9c9cc0bf34c5e95cfe7168463d310",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "SPCX",
        "name": "Space Exploration Technologies Corp. Class A Common Stock • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x4a0e65a3eccec6dbe60ae065f2e7bb85fae35eea",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x4a0e65a3eccec6dbe60ae065f2e7bb85fae35eea",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0xb265810950ba6c5c0ff821c9963014a56fd8bffb",
          "proxyAddress": "0xb265810950ba6c5c0ff821c9963014a56fd8bffb",
          "expectedDescription": "Robinhood SPCX / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 16
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000001adecf2c6a3749f9873b8926b5977c0a",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "CRWD",
        "name": "CrowdStrike Holdings • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xea72ecca2d0f6bfa1394dbbcff85b52cd4233931",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000001bbb45628de84cb2917abd26680c7ab9",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "AVGO",
        "name": "Broadcom • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x156e175dd063a8ce274c50654ef40e0032b3fbcf",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000001c6f27a62789417d8ed359ed3c2d3da1",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "SPY",
        "name": "SPDR S&P 500 ETF Trust • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x117cc2133c37b721f49de2a7a74833232b3b4c0c",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x117cc2133c37b721f49de2a7a74833232b3b4c0c",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x319724394d3a0e3669269846abe664cd621f9f6a",
          "proxyAddress": "0x319724394d3a0e3669269846abe664cd621f9f6a",
          "expectedDescription": "Robinhood SPY / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 21
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000001cf204e4aa464340bf2e68461ff6d8d3",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "CCL",
        "name": "Carnival Corporation • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x9651342cea770ae9a2969ba2a52611523146aef9",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x0000000000000000000000000000000022d137a64ac743aa991898cc4c1d7af4",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "PR",
        "name": "Permian Resources • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x4189f0c66ebbb0bfef1c31f763131361ef32f77c",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000002470b933c52d47ccad017ed9ee80c9ed",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "QQQ",
        "name": "Invesco QQQ • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xd5f3879160bc7c32ebb4dc785f8a4f505888de68",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0xd5f3879160bc7c32ebb4dc785f8a4f505888de68",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x80901d846d5d7b030f26b480776ee3b29374c2ae",
          "proxyAddress": "0x80901d846d5d7b030f26b480776ee3b29374c2ae",
          "expectedDescription": "Robinhood QQQ / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 4
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000002850ddf4a89a4195905c49a4ef7af8a5",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "NNE",
        "name": "Nano Nuclear Energy • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xbef75684c43c4ea7bd18dd532a2244674ee8b926",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000002b98fc3881db4479b3827d5ca058d31a",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "SKHY",
        "name": "SK hynix Inc. American Depositary Shares • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x84cab63bc87912e71ad199ff14a0ba45de68fef8",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000002e030d9bc86c45e2b9e02418dd312548",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "CBRS",
        "name": "Cerebras Systems • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x5c90450bbb4273d7b2f17cf6917aeb237a569679",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000002e3b98468b2d49bea9b69a2b92228fa6",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "FUTU",
        "name": "Futu Holdings • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xeb30663bdff0622ef4e4e5cbb4e975f19f33f51d",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000002e890a0884474abd86ba66b19722e827",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "TSM",
        "name": "Taiwan Semiconductor Manufacturing • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x58ffe4a942d3885baa22d7520691f611ef09e7aa",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x58ffe4a942d3885baa22d7520691f611ef09e7aa",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x874cf94aa8ec88fd9560094dd065f2fb3e41fc2f",
          "proxyAddress": "0x874cf94aa8ec88fd9560094dd065f2fb3e41fc2f",
          "expectedDescription": "Robinhood TSM / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 5
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000002ea76ec420fa43ab81d6734184f7058a",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "NU",
        "name": "Nu • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x408c14038a04f7bd235329e26d2bf569ee20e250",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000002eb75a2c20d7423881b4f812c27d0abe",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "INTC",
        "name": "Intel • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xc72b96e0e48ecd4dc75e1e45396e26300bc39681",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0xc72b96e0e48ecd4dc75e1e45396e26300bc39681",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x3f390c5c24628ac7c489515402235fead71d1913",
          "proxyAddress": "0x3f390c5c24628ac7c489515402235fead71d1913",
          "expectedDescription": "Robinhood INTC / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 30
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000307bb0113ca54f93adf80f4ff2bf681a",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "MSFT",
        "name": "Microsoft • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xe93237c50d904957cf27e7b1133b510c669c2e74",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0xe93237c50d904957cf27e7b1133b510c669c2e74",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x45c3c877c15e6ba2ebb19ea114ea508d14c1af2e",
          "proxyAddress": "0x45c3c877c15e6ba2ebb19ea114ea508d14c1af2e",
          "expectedDescription": "Robinhood MSFT / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 48
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x0000000000000000000000000000000031a6c09d095b4d49b4155de0040da68f",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "RGTI",
        "name": "Rigetti Computing • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x284358abc07f9359f19f4b5b4ac91901be2597ba",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x284358abc07f9359f19f4b5b4ac91901be2597ba",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x2a045cf1c49c61c166c036d2f06fa2d2d984f765",
          "proxyAddress": "0x2a045cf1c49c61c166c036d2f06fa2d2d984f765",
          "expectedDescription": "Robinhood RGTI / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 10
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x0000000000000000000000000000000032d0504fcc1a48ff8ac9b29185578559",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "TTWO",
        "name": "Take-Two Interactive Software • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x5e81213613b6b86eab4c6c50d718d34359459786",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000343e7beca03644bcba2e50b8236784f5",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "META",
        "name": "Meta Platforms • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xc0d6457c16cc70d6790dd43521c899c87ce02f35",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0xc0d6457c16cc70d6790dd43521c899c87ce02f35",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x7c38c00c30bee9378381e7b6135d7283356d71b1",
          "proxyAddress": "0x7c38c00c30bee9378381e7b6135d7283356d71b1",
          "expectedDescription": "Robinhood META / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 47
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x0000000000000000000000000000000036e64f28008640f9ab10ed949faf23b2",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "TSEM",
        "name": "Tower Semiconductor • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x89776d4cd68193597a2fc132cfac1fde36ccea8a",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000003bc66ed8f2314091a365604b4c01aef5",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "RDDT",
        "name": "Reddit • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x05b37fb53a299a1b874a619e1c4c404d52c36f4c",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x0000000000000000000000000000000040b2153b3d3d4715b8d22a15ba1acff2",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "GLW",
        "name": "Corning • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x7c04e6a3368f2a1de3874f0e80d2e0a1a9915da6",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000413cbb2a5e924576a297ccb67c272298",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "UPS",
        "name": "UPS • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xf23250dac154d05bb671cb0d0ebef3c635c79ce2",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x0000000000000000000000000000000046e46cc63fe842ebbdfe6187bda403d6",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "SNDK",
        "name": "Sandisk Corporation • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xb90a19ff0af67f7779aff50a882a9cff42446400",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0xb90a19ff0af67f7779aff50a882a9cff42446400",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0xfb133fa4b7b385802b693a293606682df47109a3",
          "proxyAddress": "0xfb133fa4b7b385802b693a293606682df47109a3",
          "expectedDescription": "Robinhood SNDK / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 23
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x0000000000000000000000000000000047129a8e0f8f4091841e4004bfa08013",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "BA",
        "name": "Boeing • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x4d21483a44bf67a86b77e3da301411880797d452",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000482927a418d1476c8ee89e119bf61fc7",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "INTU",
        "name": "Intuit • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x56d23bee5f41a7120170b0c603dae30128e460e9",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000004ed544ce43734899971a27f98af8972e",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "ELF",
        "name": "e.l.f. Beauty • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x39ec44bee4f6a116c6f9b8de566848a985c53c60",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000004f508d5e2a7042299694d85c2f362ad2",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "AMZN",
        "name": "Amazon • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x12f190a9f9d7d37a250758b26824b97ce941bf54",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x12f190a9f9d7d37a250758b26824b97ce941bf54",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0xd5a1508ced74c084ebf3cbe853e2c968fb2a651c",
          "proxyAddress": "0xd5a1508ced74c084ebf3cbe853e2c968fb2a651c",
          "expectedDescription": "Robinhood AMZN / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 28
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000500f14b2a92f44d6998e0e2b9cc9387e",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "NFLX",
        "name": "Netflix • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xe0444ef8bf4ed74f74fd73686e2ddf4c1c5591e8",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000005047f8f8a1a34a9ebee52a4155570807",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "CRCL",
        "name": "Circle Internet Group • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xdf0992e440dd0be65bd8439b609d6d4366bf1cb5",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0xdf0992e440dd0be65bd8439b609d6d4366bf1cb5",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x6652edf64ba3731c4f2d3ce821a0fb1f1f6b482a",
          "proxyAddress": "0x6652edf64ba3731c4f2d3ce821a0fb1f1f6b482a",
          "expectedDescription": "Robinhood CRCL / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 27
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x0000000000000000000000000000000051d8408eb0484cb6bd003337551fddd5",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "USAR",
        "name": "USA Rare Earth • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xd917b029c761d264c6a312bbbcda868658ef86a6",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x0000000000000000000000000000000053b69e2076884cc9ae2ada9bc7095df3",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "GOOGL",
        "name": "Alphabet Class A • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x2e0847e8910a9732eb3fb1bb4b70a580adad4fe3",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x2e0847e8910a9732eb3fb1bb4b70a580adad4fe3",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0xf6f373a037c30f0e5010d854385ca89185ae638b",
          "proxyAddress": "0xf6f373a037c30f0e5010d854385ca89185ae638b",
          "expectedDescription": "Robinhood GOOGL / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 2
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000005b0a57398f2f4322b011fb98da1f785f",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "LULU",
        "name": "Lululemon • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x4e62068525ab11fe768e29dfd00ef909b9803016",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000005f7e82ad6e4c4b60ba76497863fe4a67",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "SGOV",
        "name": "iShares 0-3 Month Treasury Bond • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x92fd66527192e3e61d4ddd13322aa222de86f9b5",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000612c7fa7477f4f21b3a425f180cffd86",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "IREN",
        "name": "IREN Limited • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xf0ab0c93be6f41369d302e55db1a96b3c430212d",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000006ef9da606f504495ad7de6a7a58b87cd",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "BABA",
        "name": "Alibaba • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xad25ac6c84d497db898fa1e8387bf6af3532a1c4",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0xad25ac6c84d497db898fa1e8387bf6af3532a1c4",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x62cc8f9b5f56a33c9c8a60c8b92779f523c4e984",
          "proxyAddress": "0x62cc8f9b5f56a33c9c8a60c8b92779f523c4e984",
          "expectedDescription": "Robinhood BABA / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 44
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000730835cf25474184af89c27075a82be1",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "CLSK",
        "name": "CleanSpark • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xcbb95bbf36099d34da091dc6fa6f49efa257cee3",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0xcbb95bbf36099d34da091dc6fa6f49efa257cee3",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x810c12d3a554bc47fd39597fe3b3aac4941f50ef",
          "proxyAddress": "0x810c12d3a554bc47fd39597fe3b3aac4941f50ef",
          "expectedDescription": "Robinhood CLSK / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 42
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000007454a90b4aab491389ce9fa3c485de42",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "PLTR",
        "name": "Palantir Technologies • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x894e1ec2d74ffe5aef8dc8a9e84686accb964f2a",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x894e1ec2d74ffe5aef8dc8a9e84686accb964f2a",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x820abedff239034956b7a9d2f0a331f9f075eb4c",
          "proxyAddress": "0x820abedff239034956b7a9d2f0a331f9f075eb4c",
          "expectedDescription": "Robinhood PLTR / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 8
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000007757415150a94b50a879cdc04dc90664",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "MU",
        "name": "Micron Technology • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xff080c8ce2e5feadaca0da81314ae59d232d4afd",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0xff080c8ce2e5feadaca0da81314ae59d232d4afd",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x425eefdcf05ed6526c3ce61af99429a228a6d596",
          "proxyAddress": "0x425eefdcf05ed6526c3ce61af99429a228a6d596",
          "expectedDescription": "Robinhood MU / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 32
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000778bc606b4504ca0babd4e171d5262ee",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "ASTS",
        "name": "AST SpaceMobile • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x1af6446f07eb1d97c546afc8c9544cbdf3ad5137",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000007cacd0cd4c0547d480e89459e648592b",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "RKLB",
        "name": "Rocket Lab Corporation • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x3b14c39e89d60d627b42a1a4ca45b5bb45fc12e2",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x3b14c39e89d60d627b42a1a4ca45b5bb45fc12e2",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x045477bf65aef6f4f2386ad0164579e48381cc74",
          "proxyAddress": "0x045477bf65aef6f4f2386ad0164579e48381cc74",
          "expectedDescription": "Robinhood RKLB / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 15
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000007f48cdbfaced4ff4b34fbc832f449c33",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "CRWV",
        "name": "CoreWeave • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x5f10a1c971b69e47e059e1dc91901b59b3fb49c3",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x5f10a1c971b69e47e059e1dc91901b59b3fb49c3",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0xe1b3aabcafad1c94708dc1367dcff8aa4407487c",
          "proxyAddress": "0xe1b3aabcafad1c94708dc1367dcff8aa4407487c",
          "expectedDescription": "Robinhood CRWV / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 51
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x0000000000000000000000000000000086aeaac3c7d9422c90f6fd41aff0eaf7",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "AMD",
        "name": "AMD • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x86923f96303d656e4aa86d9d42d1e57ad2023fdc",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x86923f96303d656e4aa86d9d42d1e57ad2023fdc",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x943a29e7ae51a4798823ca9eed2ed533b2a22c72",
          "proxyAddress": "0x943a29e7ae51a4798823ca9eed2ed533b2a22c72",
          "expectedDescription": "Robinhood AMD / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 52
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000008a8710f26e424b2dbc1f6b5de9f267b8",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "EWY",
        "name": "iShares MSCI South Korea fund • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x7f0abef0c07280f82c6a08ead09ded6bae2c13fc",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x7f0abef0c07280f82c6a08ead09ded6bae2c13fc",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0xefdf54610b62a7753ec30bdc380847c12d32e1d1",
          "proxyAddress": "0xefdf54610b62a7753ec30bdc380847c12d32e1d1",
          "expectedDescription": "Robinhood EWY / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 1
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000008fcfbfc7a42c40d4aa44dc7dc943b078",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "NOW",
        "name": "ServiceNow • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x0c3260af4b8f13a69c4c2dfb84fd667890cdfa14",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000008ffcea951a5b43138e764a75e22284f9",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "XLK",
        "name": "State Street Technology Select Sector SPDR ETF • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x15cd20759ce7f3285c29a319de2d1a2e098c6f43",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000915f477416294f5099a5e0e09f327ce5",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "NVDA",
        "name": "NVIDIA • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xd0601ce157db5bdc3162bbac2a2c8af5320d9eec",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0xd0601ce157db5bdc3162bbac2a2c8af5320d9eec",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x379ec4f7c378f34a1b47e4f3cbebcbac3e8e9f15",
          "proxyAddress": "0x379ec4f7c378f34a1b47e4f3cbebcbac3e8e9f15",
          "expectedDescription": "Robinhood NVDA / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 35
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x000000000000000000000000000000009448faa0b7c14ea798a7787a8cb9db5a",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "QUBT",
        "name": "Quantum Computing • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x59818904ab4ce163b3ce4ffb64f2d6ca02c434b4",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000949bd039a8ae465d9cf9336068188b55",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "USO",
        "name": "United States Oil Fund • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xa30fa36db767ad9ed3f7a60fc79526fb4d56d344",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0xa30fa36db767ad9ed3f7a60fc79526fb4d56d344",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x75a9c76ef439e2c7c2e5a34ab105ecfe3766431c",
          "proxyAddress": "0x75a9c76ef439e2c7c2e5a34ab105ecfe3766431c",
          "expectedDescription": "Robinhood USO / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 45
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000952cedaaab6e4593b884e68a4efbf481",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "F",
        "name": "Ford Motor • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x25c288e6d899b9bc30160965ad9644c67e73be0c",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000968cee5f446f422d876c7661ff20b373",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "ZS",
        "name": "Zscaler • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x7dc013eb55e436f30d7ed1afe4e36d6e45e3c3f7",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000970b46dbdece4ae4958a53815e62a85a",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "COIN",
        "name": "Coinbase • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x6330d8c3178a418788df01a47479c0ce7ccf450b",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x6330d8c3178a418788df01a47479c0ce7ccf450b",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0xa3a468a452940b7d6b69991207b508c609a98ef2",
          "proxyAddress": "0xa3a468a452940b7d6b69991207b508c609a98ef2",
          "expectedDescription": "Robinhood COIN / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 7
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x0000000000000000000000000000000098d983331a5245e98847e635b93eb920",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "XOM",
        "name": "ExxonMobil Holdings Corporation • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xf9b46d3d1b22199d4d1025a9cedb540a33f1a2d5",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000994b82ab24514d439fccc87156df35f9",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "NBIS",
        "name": "Nebius Group • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x9d9c6684f596f66a64c030b93a886d51fd4d7931",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x9d9c6684f596f66a64c030b93a886d51fd4d7931",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0xe1d87b116ba0fe898998f1d140339d1fa1e09705",
          "proxyAddress": "0xe1d87b116ba0fe898998f1d140339d1fa1e09705",
          "expectedDescription": "Robinhood NBIS / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 40
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000a20e50a9f81946d58dafdad20661ec10",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "POET",
        "name": "POET Technologies • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xcf6b2d875361be807eafa57458c80f28521f9333",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000a47bbc4c8a0b4f44a6d1aff3242b3088",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "AAOI",
        "name": "Applied Optoelectronics • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x521cf887e6531c6f667b5bc4d896e5d9bfe8eb2e",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000a5fc7b0af972454baf7c124f624ae97f",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "LITE",
        "name": "Lumentum • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x8ef20885f94e3d9bc7eb3080279188bd5ed7c08c",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000a98d1e2ff1ea4e54a538680595585902",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "AMAT",
        "name": "Applied Materials • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x36046893810a7e7fce501229d57dc3fc8c8716d0",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000aa33b104a54c4de08cc929fb8e8af349",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "MRVL",
        "name": "Marvell Technology • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x62fd0668e10d8b72339be2dcf7643001688ff13b",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000ac7debdd1135468e9b6a35678f81bb28",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "LLY",
        "name": "Eli Lilly • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x8005d266423c7ea827372c9c864491e5786600ea",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000ad4edb65cfed4b93a3f768502f7ac2b2",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "QCOM",
        "name": "Qualcomm • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x0f17206447090e464c277571124dd2688e48aea9",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000b6f6e756b7ff46b88238c18d0bc07fd4",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "IONQ",
        "name": "IonQ • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x558378e000d634a36593e338ebacdd6207640efe",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x558378e000d634a36593e338ebacdd6207640efe",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x22efec4919baf55f360e0edee4abeb26de4971eb",
          "proxyAddress": "0x22efec4919baf55f360e0edee4abeb26de4971eb",
          "expectedDescription": "Robinhood IONQ / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 25
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000b82496d605ca4b019c9200daa049f52f",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "SHOP",
        "name": "Shopify • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xf53f66751b1eff985311b693531e3290f600c410",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000b9e9686fc0904e87aef5134b823020e3",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "NVTS",
        "name": "Navitas Semiconductor • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xbe6702d7b70315376dc48a3293f24f0982f86386",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000bb970311792440cebde7cef41f80d446",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "UMC",
        "name": "United Microelectronics • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x0e6e67ba88e7b5d9b67636a215c76779b948de79",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000be23b7c535e841a3b1bae97bc0166eae",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "ORCL",
        "name": "Oracle • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xb0992820e760d836549ba69bc7598b4af75dee03",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0xb0992820e760d836549ba69bc7598b4af75dee03",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x0e6a64a2b58a6693a531e6c555f3a5d042eea844",
          "proxyAddress": "0x0e6a64a2b58a6693a531e6c555f3a5d042eea844",
          "expectedDescription": "Robinhood ORCL / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 12
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000c23820045b544bafbdc0dd622098fcc3",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "INOD",
        "name": "Innodata • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xf1953dab6fad537488d5a022361ffaa8b4c95ec6",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000c2425be3658540dd8e2424cbf3c5c649",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "AAPL",
        "name": "Apple • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xaf3d76f1834a1d425780943c99ea8a608f8a93f9",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0xaf3d76f1834a1d425780943c99ea8a608f8a93f9",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x6b22a786baa607d76728168703a39ea9c99f2cd0",
          "proxyAddress": "0x6b22a786baa607d76728168703a39ea9c99f2cd0",
          "expectedDescription": "Robinhood AAPL / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 33
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000c4aa88df91204d23a4ff43cd0768298d",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "RIVN",
        "name": "Rivian Automotive • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xb1bf26c1d20ff267a4f93550d1e0d06ac40a114b",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000c5ac9420091c4f9eb3ff1fdd1d2b60c6",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "GME",
        "name": "GameStop • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x1b0e319c6a659f002271b69db8a7df2f911c153e",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x1b0e319c6a659f002271b69db8a7df2f911c153e",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x27c71df6a64fb476468edf256cf72c038bab5b67",
          "proxyAddress": "0x27c71df6a64fb476468edf256cf72c038bab5b67",
          "expectedDescription": "Robinhood GME / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 53
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000c6257ac357d34120ba22c2589ba17cc9",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "PENG",
        "name": "Penguin Solutions • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x9b23573b156b52565012f5ce02cdf60afbaa70be",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000c8fa21fd16c744c9ac5c7f5a60ca433a",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "LUNR",
        "name": "Intuitive Machines • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xa5d4968421ba94814be3b136b15cf422101ac1a3",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000c91ba6e57a1c493f99cae2174e43c86e",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "MSTR",
        "name": "Strategy Inc. • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xec262a75e413fafd0df80480274532c79d42da09",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0xec262a75e413fafd0df80480274532c79d42da09",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x396118bdfb181e6240e74d243f266b061c0edc3d",
          "proxyAddress": "0x396118bdfb181e6240e74d243f266b061c0edc3d",
          "expectedDescription": "Robinhood MSTR / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 13
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000cfece3244ea34bb29414dd9488b32d9f",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "TSLA",
        "name": "Tesla • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x322f0929c4625ed5bad873c95208d54e1c003b2d",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x322f0929c4625ed5bad873c95208d54e1c003b2d",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x4a1166a659a55625345e9515b32adecea5547c38",
          "proxyAddress": "0x4a1166a659a55625345e9515b32adecea5547c38",
          "expectedDescription": "Robinhood TSLA / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 22
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000d491ee29c5564368830ce787289dcae8",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "XNDU",
        "name": "Xanadu Quantum • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xa8eb3bccbf2017ee7cbfb652eb51cf2e1b153289",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000d4bd519623e545bf91b7ea590c66801e",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "DDOG",
        "name": "Datadog • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x27c99fbde9d0d2aa4f4bfb4943f237843ddf6958",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000d6571fe1a63748a4b7b79b37612dc9b8",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "RDW",
        "name": "Redwire • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x92ef19e82bd8ff36661de838d5eae7e5cef0effe",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000d73a53e43ed744d4b5d42c5293ba51ad",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "BE",
        "name": "Bloom Energy • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x822cc93ffd030293e9842c30bbd678f530701867",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000da64fede272447a3b772423f0962a984",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "ZM",
        "name": "Zoom • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x44c4f142009036cf477ed2d09932051843137cf1",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000dceece67a8c740f180047f65ccb4c44a",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "FLNC",
        "name": "Fluence Energy • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x282e87451e10fa6679bc7d76c69be44cd3fc777c",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000ddf030d4e25046cab85b3d8c7cd86553",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "SLV",
        "name": "iShares Silver Trust • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x411efb0e7f985935daec3d4c3ebaea0d0ad7d89f",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x411efb0e7f985935daec3d4c3ebaea0d0ad7d89f",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0x209b73908e92ae021826ed79609845451ecba2ce",
          "proxyAddress": "0x209b73908e92ae021826ed79609845451ecba2ce",
          "expectedDescription": "Robinhood SLV / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 50
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000df2cb1370b1b41a8b896a706fefae931",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "SOFI",
        "name": "SoFi Technologies • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x98e75885157c80992a8d41b696d8c9c6fb30a926",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000e0e44220991548d0b030699e3062c2a7",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "COST",
        "name": "Costco • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x4ea005168d7f09a7a0ba9d1def21a479950e44c2",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000e5c73eb672384c37ab8554f9ebe3131a",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "CELH",
        "name": "Celsius • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x8cf07c5a878945185d327aaa6e33faa95f95e7bf",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000eed533334fe84ce08253d5b1dcff7373",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "RBLX",
        "name": "Roblox • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xf0c4bf4c582cb3836e98394b1d4e7b7281101be8",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000eefd305f8fd04bdb882b158b0b30d776",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "SPMO",
        "name": "Invesco S&P 500 Momentum ETF • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xad622320e520de39e72d41ef07438c3fd3354875",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000f379ff90efb54b4cb6280fc923e38926",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "SOXX",
        "name": "iShares Semiconductor ETF • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x75742c18bc1f1c5c5f448f4c9d9c6f66dafaaa38",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000f6e013126d524981acc9df053b0c19ea",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "ASML",
        "name": "ASML Holding NV • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0x47f93d52cbec7c6d2cfc080e154002370a60daea",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "mapped",
        "selectedDeployment": {
          "chainId": 4663,
          "contractAddress": "0x47f93d52cbec7c6d2cfc080e154002370a60daea",
          "networkName": "Robinhood Chain"
        },
        "feed": {
          "feedId": "0xb4106147e8cce40b7d46124090d373a71b70f87d",
          "proxyAddress": "0xb4106147e8cce40b7d46124090d373a71b70f87d",
          "expectedDescription": "Robinhood ASML / USD",
          "decimals": 8,
          "heartbeatSeconds": 86400,
          "availability": "session_dependent_24_5",
          "sourceRow": 43
        }
      }
    },
    {
      "asset": {
        "assetUid": "0x00000000000000000000000000000000f92f60961bbe43028a23a3d52174b320",
        "sourceStatus": "ASSET_STATUS_ACTIVE",
        "symbol": "MDB",
        "name": "MongoDB • Robinhood Token",
        "deployments": [
          {
            "chainId": 4663,
            "contractAddress": "0xddf2266b79abf0b48898959b0ed6e6adf512be74",
            "networkName": "Robinhood Chain"
          }
        ]
      },
      "mapping": {
        "status": "unmapped",
        "reason": "feed_not_found"
      }
    }
  ]
} as const;
